apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2  # 1️⃣ On passe à 2 répliques comme sur ton schéma
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # 2️⃣ ON SUPPRIME "nodeName: worker2" pour laisser K8s répartir sur Worker 1 et Worker 2
      containers:
      - name: frontend
        image: 192.168.56.20:5000/mon-app-frontend:v37 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001