apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-manager-binding
  namespace: mon-projet
subjects:
- kind: Group
  name: dev-team
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: application-manager
  apiGroup: rbac.authorization.k8s.io